config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root to: "users#index", as: :authenticated_root
  end

  unauthenticated :user do
    root to: "devise/sessions#new", as: :unauthenticated_root
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post # start by defining rules for all users, also not logged ones
    return unless user.present?

    # if the user is logged in can create posts, comments and likes
    can :create, Post
    can :create, Comment
    can :create, Like

    can :destroy, Post, author_id: user.id # if the user is logged in can delete it's own posts
    can :destroy, Comment, user_id: user.id # if the user is logged in can delete it's own comments
    can :destroy, Like, user_id: user.id # if the user is logged in can delete it's own likes
    return unless user.role == 'admin'

    can :manage, :all # give all remaining permissions only to the admins

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to can is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
# app/models/user.rb

class User < ApplicationRecord
  # Devise modules including :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Associations
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  # Validations
  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Custom method to retrieve three most recent posts
  def three_recent_posts
    posts.order(created_at: :desc).first(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout 'standard'
  before_action :find_post
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :authorize_comment, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = 'Comment created successfully!'
      redirect_to user_post_path(id: @comment.post_id, user_id: @comment.user_id)
    else
      flash.now[:error] = 'Error: Comment could not be created!'
      render :new, locals: { comment: @comment }
    end
  end

  def edit
    # @comment is already loaded by the before_action
  end

  def update
    if @comment.update(comment_params)
      flash[:success] = 'Comment updated successfully!'
      redirect_to user_post_path(id: @comment.post_id, user_id: @comment.user_id)
    else
      flash.now[:error] = 'Error: Comment could not be updated!'
      render :edit, locals: { comment: @comment }
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'Comment deleted successfully!'
    redirect_to user_post_path(id: @comment.post_id, user_id: @comment.user_id)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def authorize_comment
    authorize! params[:action].to_sym, @comment
  end

  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  layout 'standard'
  def create
    @like = Like.new(post_id: params[:post_id], user_id: params[:user_id])
    @like.user = current_user
    if @like.save
      flash[:success] = 'Liked!'
      redirect_to user_post_path(id: @like.post_id, user_id: @like.user_id)
    else
      flash.now[:error] = 'Something went wrong!'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'standard'

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).order(id: :asc).paginate(page: params[:page], per_page: 5)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      flash[:success] = 'Post created successfully!'
      redirect_to user_post_url(current_user, @post)
    else
      flash.now[:error] = 'Error: Post could not be created!'
      render :new, locals: { post: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:success] = 'Post updated successfully!'
      redirect_to user_post_url(current_user, @post)
    else
      flash.now[:error] = 'Error: Post could not be updated!'
      render :edit, locals: { post: @post }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    flash[:success] = 'Post deleted successfully!'
    redirect_to user_posts_url(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'standard'
  def index
    @users = User.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/new.html.erb
<%= form_with model: [:user, @post, @comment], url: (@comment.new_record? ? user_post_comments_path(user_id: current_user, post_id: @post) : user_post_comment_path(user_id: current_user, post_id: @post, id: @comment)), method: (@comment.new_record? ? :post : :patch), data: { turbo: false }, local: true do |f| %>
  <div>
    <%= f.label :text %><br>
    <%= f.text_field :text %><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit @comment.new_record? ? "Comment" : "Update Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

   <body>

      <div id = "container">
        <%= yield -%>
      </div>

   </body>
   
</html>

app/views/likes/_like_action.html.erb
<%# <% if post.likes.indlude?(current_user.id) %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= form_with model: @like, url: user_post_likes_path(post_id: post.id, user_id: post.author_id), data: { turbo: false }, local: true, scope: :like do |f| %>
  <div>
    <%= f.hidden_field :user_id, value: :user_id %>
    <%= f.hidden_field :post_id, value: :post_id %>
    <%= f.submit "Like this post" %>
  </div>
<% end %>

app/views/likes/_like_post.html.erb
<%# <% if post.likes.indlude?(current_user.id) %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= form_with model: @like, url: user_post_likes_path(post_id: post.id, user_id: post.author_id), data: { turbo: false }, local: true, scope: :like do |f| %>
  <div>
    <%= f.hidden_field :user_id, value: :user_id %>
    <%= f.hidden_field :post_id, value: :post_id %>
    <%= f.submit "Like this post" %>
  </div>
<% end %>

app/views/posts/_post_info.html.erb
<h3><%= post.title %></h3>
<p><%= truncate(post.text, length: 100, omission: '...') %></p>
<p class="counter">
  Comments: <%= post.comments_counter.to_i %>, Likes: <%= post.likes_counter.to_i %>
</p>

app/views/posts/_post_user.erb
<h3><%= post.title %></h3>
<p><%= truncate(post.text, length: 100, omission: '...') %></p>
<p class="counter">
  Comments: <%= post.comments_counter.to_i %>, Likes: <%= post.likes_counter.to_i %>
</p>

app/views/posts/index.html.erb
<div class="user">
  <%= render partial: "users/user_info", locals: { user: @user } %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= link_to 'Create New Post', new_user_post_path %>

<ul id="posts_container">
  <% @posts.each do |post| %>
    <li>
      <%= link_to user_post_path(@user, post), class: "post" do %>
        <%= render partial: "posts/post_info", locals: { post: post } %>
      <% end %>
      <ul class="comments_container">
        <h3>Comments:</h3>
        <% post.five_recent_comments.includes([:user]).each do |comment| %>
          <li class="comment">
            <p><%= "#{comment.user.name}: #{comment.text}" %></p>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= form_with model: [:user, @post], data: { turbo: false }, local: true do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label :text %><br>
    <%= f.text_area :text %><br>
    <%= f.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="post">
  <h3><%= @post.title %> by <%= @post.author.name %></h3>
  <p class="counter">
    Comments: <%= @post.comments_counter.to_i %>, Likes: <%= @post.likes_counter.to_i %>
  </p>
  <p><%= @post.text %></p>

  <% if can? :update, @post %>
    <%= link_to 'Edit', edit_user_post_path(current_user, @post) %> |
  <% end %>

  <% if can? :destroy, @post %>
    <%= link_to 'Delete', user_post_path(current_user, @post), method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>

</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<ul class="comments_container">
  <% @post.comments.includes([:user]).each do |comment| %>
    <li class="comment">
      <p><%= "#{comment.user.name}: #{comment.text}" %></p>

      <% if can? :update, comment %>
        <%= link_to 'Edit', edit_user_post_comment_path(current_user, @post, comment) %> |
      <% end %>

      <% if can? :destroy, comment %>
        <%= link_to 'Delete', user_post_comment_path(current_user, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= render partial: "likes/like_action", locals: { post: @post } %>
<%= link_to 'New Comment', new_user_post_comment_path(current_user, post_id: @post.id) %>

app/views/users/_user_info.html.erb
<img src=<%= user.photo %> class="user_photo" alt="a_user">
<div class="user_text">
  <h2><%= user.name %></h2><br>
  <p>Number of posts: <%= user.posts_counter.to_i %></p>
</div>

app/views/users/_user_user.erb
<!-- app/views/users/_user_user.html.erb -->
<img src=<%= user.photo %> class="user_photo" alt="a_user">
<div class="user_text">
  <h2><%= user.name %></h2><br>
  <p>Number of posts: <%= user.posts_counter.to_i %></p>
</div>

app/views/users/index.html.erb
<ul id="users_container">
  <% @users.each do |user| %>
    <li>
      <%= link_to user_url(user), class: "user", id: user.name do %>
        <%= render partial: "users/user_info", locals: { user: user } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="user">
  <%= render partial: "users/user_info", locals: { user: @user } %>
</div>

<div id="user_bio">
  <h3>Bio</h3>
  <p><%= @user.bio %></p>
</div>

<div id="posts_container">
  <% @user.three_recent_posts.each do |post| %>
    <li>
      <%= link_to user_post_path(@user, post), class: "post", id: post.id do %>
        <%= render partial: "posts/post_info", locals: { post: post } %>
      <% end %>
    </li>
  <% end %>
</div>

<%= link_to "See all posts", user_posts_path(@user, page: 1) %>